# ----------------------------------------------------------------------------------------------------------------------
# Artemis base service
# ----------------------------------------------------------------------------------------------------------------------

# Initially copied from https://github.com/HOME-programming-pub/Artemis/blob/2a608e52f7835ca4346948407a21adca58467089/docker/artemis.yml

networks:
    artemis:
        name: artemis
volumes:
    artemis-data:
        name: HOME-artemis-data # /opt/artemis/data
    artemis-content:
        name: HOME-artemis-content # /opt/artemis/public/content
    artemis-config:
        name: HOME-artemis-config # /opt/artemis/config

services:
    artemis-app:
        container_name: artemis-app
        platform: linux/amd64
        image: ghcr.io/ls1intum/artemis:latest
        restart: always
        hostname: 'artemis' # container-internal name
        build:
            context: ..
            dockerfile: docker/artemis/Dockerfile
            pull: true
            target: runtime
        volumes:
            - artemis-data:/opt/artemis/data
            - artemis-content:/opt/artemis/public/content
            - artemis-config:/opt/artemis/config
            - ./artemis/certs:/opt/artemis/certs
            - ./artemis/java-certs/cacerts:/opt/java/openjdk/lib/security/cacerts
        # system environments are the default way for custom configuration overrides in the containerized artemis setups
        # either add them in the environments or env_file section (alternative to application-local.yml)
        env_file:
            - ./artemis/config/prod-application-local.env
        # if you need to use another port than 8080 or one fixed port for all artemis-app containers in the future
        # you will probably not be able to override this setting outside the artemis.yml
        # as stated in the docker compose docs (at least not when this was committed)
        # https://docs.docker.com/compose/compose-file/#finding-referenced-service
        healthcheck:
            test: wget -nv -t1 --spider http://localhost:8080/actuator/health || exit 1
            start_period: 600s
            interval: 1s
        # expose the port to make it reachable docker internally even if the external port mapping changes
        expose:
            - "8080"
            - "8089"
        ports:
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:8089:8089"
        networks:
            - artemis

